version: '3'
services:
  gerrit:
    image: gerritcodereview/gerrit
    container_name: gerrit
    environment:
      - CANONICAL_WEB_URL=${GERRIT_WEBURL}
    ports:
      - "${GERRIT_SSH_PORT}:${GERRIT_CONTAINER_SSH_PORT}"
    volumes:
      - ./gerrit/etc:/var/gerrit/etc
    networks:
      - gerrit-network
    restart: unless-stopped

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # 预配置gitlab.rb中的配置项，每行一项
        external_url '${GITLAB_WEBURL}'
        gitlab_rails['gitlab_shell_ssh_host'] = '${HOST}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        puma['worker_processes'] = 2
        sidekiq['concurrency'] = 10
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
    ports:
      - '${GITLAB_SSH_PORT}:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - gerrit-network
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "${PORT}:${NGINX_CONTAINER_PORT}"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/htpasswd/.htpasswd:/etc/nginx/htpasswd
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - gerrit
      - gitlab
    networks:
      - gerrit-network
    restart: unless-stopped

networks:
  gerrit-network:
    driver: bridge

